leftnav:
- identifier: 329f8a69-e156-d8be-fb1b-4802c45e5546
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: bcbf0d9c-e978-965b-8de5-9e770f06b490
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: 40ce783f-f31e-d750-d8ab-3fb0cc415acb
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 30
- identifier: 5e61fdfa-4d08-2641-3d10-153f8aef1e09
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: e0a86cae-eb3d-c96c-14bf-3687718352e8
  name: Exams
  url: /pages/exams
  weight: 50
